CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(30)                             NOT NULL,
    uri       VARCHAR(100)                            NOT NULL,
    ip        VARCHAR(20)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);