CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(30)                             NOT NULL,
    uri       VARCHAR(30)                             NOT NULL,
    ip        VARCHAR(20)                             NOT NULL,
    timestamp VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS view_stats
(
    app  VARCHAR(30) NOT NULL,
    uri  VARCHAR(30) NOT NULL,
    hits BIGINT DEFAULT (0),
    constraint pk_view_stats PRIMARY KEY (app, uri)
);